version: '3.9'

services:
  web:
    build: .
    env_file:
      - .env        # injects all secrets into container
    ports:
      - "8000:8000"
    volumes:
      - .:/app      # live reload if needed
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn AgentTrader.wsgi:application --bind 0.0.0.0:8000"
