# Generated by Django 5.2.8 on 2026-03-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0002_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auto_trade_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='broker_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='broker_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='risk_per_trade',
            field=models.FloatField(default=1.0),
        ),
    ]
