# Generated by Django 5.2.8 on 2026-03-27 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0003_customuser_auto_trade_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='auto_trade_enabled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='broker_account_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='broker_api_key',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='risk_per_trade',
        ),
        migrations.CreateModel(
            name='TraderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_profit_loss', models.FloatField(default=0.0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('risk_reward_ratio', models.FloatField(default=0.0)),
                ('max_drawdown', models.FloatField(default=0.0)),
                ('sharpe_ratio', models.FloatField(default=0.0)),
                ('trade_accuracy', models.FloatField(default=0.0)),
                ('auto_trading', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('MANUAL', 'Manual'), ('SEMI', 'Semi-auto'), ('FULL', 'Full auto')], default='MANUAL', max_length=10)),
                ('allowed_symbols', models.TextField(default='EUR/USD,GBP/USD,USD/JPY,EUR/JPY')),
                ('allowed_timeframes', models.TextField(default='15min,30min,1h')),
                ('trade_size_strategy', models.CharField(choices=[('FIXED', 'Fixed lot'), ('RISK', 'Risk-based')], default='FIXED', max_length=10)),
                ('fixed_lot_size', models.FloatField(default=0.01)),
                ('risk_per_trade', models.FloatField(default=1.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
